package netgloo.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import java.util.Date;


/**
 * An Job entity
 */
@Entity
@Table(name = "jobs")
public class Job {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // Job id from external service
  @NotNull
  private String externalId;
  
  //Title or position of the job
  @NotNull
  private String position;

  //Organization for the job
  @NotNull
  private String organization;

  @NotNull
  private String rateIntervalCode;

  //Minimum Salary
  @NotNull
  private Integer minimumSalary;

  //Maximum Salary
  @NotNull
  private Integer maximumSalary;

  //Job start date
  @NotNull
  private Date startDate;

  //Job end date
  @NotNull
  private Date endDate;

  //TODO Locations
  @NotNull
  private String url;

 
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Job() { }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getExternalId(){
    return this.externalId;
  }
  
  public void setExternalId(String externalId){
    this.externalId = externalId;
  }

  public String getPosition(){
    return this.position;
  }
  
  public void setPosition(String position){
    this.position = position;
  }

  public String getOrganization(){
    return this.organization;
  }
  
  public void setOrganization(String organization){
    this.organization = organization;
  }

  public String getRateIntervalCode(){
    return this.rateIntervalCode;
  }
  
  public void setRateIntervalCode(String rateIntervalCode){
    this.rateIntervalCode = rateIntervalCode;
  }

  public Integer getMinimumSalary(){
    return this.minimumSalary;
  }
  
  public void setMinimumSalary(Integer minimumSalary){
    this.minimumSalary = minimumSalary;
  }

  public Integer getMaximumSalary(){
    return this.maximumSalary;
  }
  
  public void setMaximumSalary(Integer maximumSalary){
    this.maximumSalary = maximumSalary;
  }

  public Date getStartDate(){
    return this.startDate;
  }
  
  public void setStartDate(Date startDate){
    this.startDate = startDate;
  }

  public Date getEndDate(){
    return this.endDate;
  }
  
  public void setEndDate(Date endDate){
    this.endDate = endDate;
  }


   public String getURl(){
    return this.url;
  }
  
  public void setURL(String url){
    this.url = url;
  }

} // class Job
