package netgloo.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;


/**
 * An Job entity
 */
@Entity
@Table(name = "locations")
public class Location {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // Job id from external service
  @NotNull
  private String name;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "job_id", nullable = false)
  private Job job;
  

 
  public Location() { }

   public Location(String name) { 
     this.name = name;
   }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getName(){
    return this.name;
  }
  
  public void setName(String name){
    this.name = name;
  }

  public Job getJob(){
    return this.job;
  }
  
  public void setJob(Job job){
    this.job = job;
  }

} // class Location
