package jobs.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Location entity
 * 
 * @author Denis Bell <http://denisdbell.com>
 */
@Entity
@Table(name = "locations")
public class Location {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;

  @NotNull
  private String name;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "job_id", nullable = false)
  private Job job;

  public Location() {
  }

  public Location(String name) {
    this.name = name;
  }

  public long getId() {
    return id;
  }

  public void setId(long value) {
    this.id = value;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @JsonIgnore
  public Job getJob() {
    return this.job;
  }

  public void setJob(Job job) {
    this.job = job;
  }

} // class Location
